### ISSUE TITLE
consider ability to like own posts

### ISSUE THREAD

**Issue by saddington** [yenio/changelog#49]
https://beta.yen.io/andrew/status/154092811888620

should we be allowed to like your own posts?

**Comment by saddington** [comment]
@james-yen we can already do this...

**Comment by saddington** [comment]
and this is normative behavior... right? twitter does this.

**Comment by james-yen** [comment]
@saddington yeah we can do it now, but he's asking if we _should_ be able to. I think we should keep it but worth a quick discussion.

**Comment by heavilyarmedclown** [comment]
Keep it. No harm no foul.

**Comment by saddington** [comment]
@heavilyarmedclown ... for now. yes, but, i love that our community is actively thinking through this!
